#######
# Compiled from data/chillpack/functions/button_detector.mcscript
# to .//chillpack/data/chillpack/functions/button_detector.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @p at @p if block ~1 ~ ~ minecraft:stone_button[powered=true] run function chillpack:grind_biome
execute as @p at @p if block ~-1 ~ ~ minecraft:stone_button[powered=true] run function chillpack:grind_biome
execute as @p at @p if block ~ ~1 ~ minecraft:stone_button[powered=true] run function chillpack:grind_biome
execute as @p at @p if block ~ ~-1 ~ minecraft:stone_button[powered=true] run function chillpack:grind_biome
execute as @p at @p if block ~ ~ ~1 minecraft:stone_button[powered=true] run function chillpack:grind_biome
execute as @p at @p if block ~ ~ ~-1 minecraft:stone_button[powered=true] run function chillpack:grind_biome