#######
# Compiled from data/chillpack/functions/grind_biome.mcscript
# to .//chillpack/data/chillpack/functions/grind_biome.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if entity @p[scores={Grind_Timer=200..}] if predicate chillpack:forest run function chillpack:biome/forest
execute if predicate chillpack:badlands run function chillpack:biome/badlands