#######
# Compiled from data/chillpack/functions/load.mcscript
# to .//chillpack/data/chillpack/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function chillpack:mcscript/load

scoreboard objectives add Grind_Timer dummy "Grind Timer"
scoreboard objectives setdisplay sidebar Grind_Timer