#######
# Compiled from chillpack/functions/biome/badlands.mcscript
# to .//chillpack/data/chillpack/functions/biome/badlands.mcfunction
#
# Generated by Minecraft Script for 1.16
######
say "in badlands"