# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2
sphinx:
  builder: html
  configuration: docs_src/conf.py
python:
  version: 3.8
  install:
    - method: pip
      path: .
  system_packages: true
