#######
# Compiled from chillpack/functions/scoreboard/tick.mcscript
# to .//chillpack/data/chillpack/functions/scoreboard/tick.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set @p[scores={Grind_Timer=1000..}] Grind_Timer 0 
scoreboard players add @p Grind_Timer 1