#######
# Compiled from chillpack/functions/scoreboard/time_checker.mcscript
# to .//chillpack/data/chillpack/functions/scoreboard/time_checker.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set @p[scores={Grind_Timer=300..}] Grind_Timer 0 